# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/1507/bin/cmake

# The command to remove a file.
RM = /snap/cmake/1507/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/orville/dev/talawa-ai

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/orville/dev/talawa-ai

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/snap/cmake/1507/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/snap/cmake/1507/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/orville/dev/talawa-ai/CMakeFiles /home/orville/dev/talawa-ai//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/orville/dev/talawa-ai/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named talawa-ai

# Build rule for target.
talawa-ai: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 talawa-ai
.PHONY : talawa-ai

# fast build rule for target.
talawa-ai/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/talawa-ai.dir/build.make CMakeFiles/talawa-ai.dir/build
.PHONY : talawa-ai/fast

#=============================================================================
# Target rules for targets named cnn_mnist.test

# Build rule for target.
cnn_mnist.test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cnn_mnist.test
.PHONY : cnn_mnist.test

# fast build rule for target.
cnn_mnist.test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnn_mnist.test.dir/build.make CMakeFiles/cnn_mnist.test.dir/build
.PHONY : cnn_mnist.test/fast

#=============================================================================
# Target rules for targets named matrix.test

# Build rule for target.
matrix.test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 matrix.test
.PHONY : matrix.test

# fast build rule for target.
matrix.test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix.test.dir/build.make CMakeFiles/matrix.test.dir/build
.PHONY : matrix.test/fast

#=============================================================================
# Target rules for targets named matrix_equality.test

# Build rule for target.
matrix_equality.test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 matrix_equality.test
.PHONY : matrix_equality.test

# fast build rule for target.
matrix_equality.test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix_equality.test.dir/build.make CMakeFiles/matrix_equality.test.dir/build
.PHONY : matrix_equality.test/fast

#=============================================================================
# Target rules for targets named mnist.test

# Build rule for target.
mnist.test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mnist.test
.PHONY : mnist.test

# fast build rule for target.
mnist.test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mnist.test.dir/build.make CMakeFiles/mnist.test.dir/build
.PHONY : mnist.test/fast

#=============================================================================
# Target rules for targets named net.test

# Build rule for target.
net.test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 net.test
.PHONY : net.test

# fast build rule for target.
net.test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net.test.dir/build.make CMakeFiles/net.test.dir/build
.PHONY : net.test/fast

#=============================================================================
# Target rules for targets named save_load.test

# Build rule for target.
save_load.test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 save_load.test
.PHONY : save_load.test

# fast build rule for target.
save_load.test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/save_load.test.dir/build.make CMakeFiles/save_load.test.dir/build
.PHONY : save_load.test/fast

#=============================================================================
# Target rules for targets named Matrix.benchmark

# Build rule for target.
Matrix.benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Matrix.benchmark
.PHONY : Matrix.benchmark

# fast build rule for target.
Matrix.benchmark/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Matrix.benchmark.dir/build.make CMakeFiles/Matrix.benchmark.dir/build
.PHONY : Matrix.benchmark/fast

benchmarks/Matrix.benchmark.o: benchmarks/Matrix.benchmark.cpp.o
.PHONY : benchmarks/Matrix.benchmark.o

# target to build an object file
benchmarks/Matrix.benchmark.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Matrix.benchmark.dir/build.make CMakeFiles/Matrix.benchmark.dir/benchmarks/Matrix.benchmark.cpp.o
.PHONY : benchmarks/Matrix.benchmark.cpp.o

benchmarks/Matrix.benchmark.i: benchmarks/Matrix.benchmark.cpp.i
.PHONY : benchmarks/Matrix.benchmark.i

# target to preprocess a source file
benchmarks/Matrix.benchmark.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Matrix.benchmark.dir/build.make CMakeFiles/Matrix.benchmark.dir/benchmarks/Matrix.benchmark.cpp.i
.PHONY : benchmarks/Matrix.benchmark.cpp.i

benchmarks/Matrix.benchmark.s: benchmarks/Matrix.benchmark.cpp.s
.PHONY : benchmarks/Matrix.benchmark.s

# target to generate assembly for a file
benchmarks/Matrix.benchmark.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Matrix.benchmark.dir/build.make CMakeFiles/Matrix.benchmark.dir/benchmarks/Matrix.benchmark.cpp.s
.PHONY : benchmarks/Matrix.benchmark.cpp.s

src/core/Activation.o: src/core/Activation.cpp.o
.PHONY : src/core/Activation.o

# target to build an object file
src/core/Activation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/talawa-ai.dir/build.make CMakeFiles/talawa-ai.dir/src/core/Activation.cpp.o
.PHONY : src/core/Activation.cpp.o

src/core/Activation.i: src/core/Activation.cpp.i
.PHONY : src/core/Activation.i

# target to preprocess a source file
src/core/Activation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/talawa-ai.dir/build.make CMakeFiles/talawa-ai.dir/src/core/Activation.cpp.i
.PHONY : src/core/Activation.cpp.i

src/core/Activation.s: src/core/Activation.cpp.s
.PHONY : src/core/Activation.s

# target to generate assembly for a file
src/core/Activation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/talawa-ai.dir/build.make CMakeFiles/talawa-ai.dir/src/core/Activation.cpp.s
.PHONY : src/core/Activation.cpp.s

src/core/Initializer.o: src/core/Initializer.cpp.o
.PHONY : src/core/Initializer.o

# target to build an object file
src/core/Initializer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/talawa-ai.dir/build.make CMakeFiles/talawa-ai.dir/src/core/Initializer.cpp.o
.PHONY : src/core/Initializer.cpp.o

src/core/Initializer.i: src/core/Initializer.cpp.i
.PHONY : src/core/Initializer.i

# target to preprocess a source file
src/core/Initializer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/talawa-ai.dir/build.make CMakeFiles/talawa-ai.dir/src/core/Initializer.cpp.i
.PHONY : src/core/Initializer.cpp.i

src/core/Initializer.s: src/core/Initializer.cpp.s
.PHONY : src/core/Initializer.s

# target to generate assembly for a file
src/core/Initializer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/talawa-ai.dir/build.make CMakeFiles/talawa-ai.dir/src/core/Initializer.cpp.s
.PHONY : src/core/Initializer.cpp.s

src/core/Matrix.o: src/core/Matrix.cpp.o
.PHONY : src/core/Matrix.o

# target to build an object file
src/core/Matrix.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/talawa-ai.dir/build.make CMakeFiles/talawa-ai.dir/src/core/Matrix.cpp.o
.PHONY : src/core/Matrix.cpp.o

src/core/Matrix.i: src/core/Matrix.cpp.i
.PHONY : src/core/Matrix.i

# target to preprocess a source file
src/core/Matrix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/talawa-ai.dir/build.make CMakeFiles/talawa-ai.dir/src/core/Matrix.cpp.i
.PHONY : src/core/Matrix.cpp.i

src/core/Matrix.s: src/core/Matrix.cpp.s
.PHONY : src/core/Matrix.s

# target to generate assembly for a file
src/core/Matrix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/talawa-ai.dir/build.make CMakeFiles/talawa-ai.dir/src/core/Matrix.cpp.s
.PHONY : src/core/Matrix.cpp.s

src/core/Optimizer.o: src/core/Optimizer.cpp.o
.PHONY : src/core/Optimizer.o

# target to build an object file
src/core/Optimizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/talawa-ai.dir/build.make CMakeFiles/talawa-ai.dir/src/core/Optimizer.cpp.o
.PHONY : src/core/Optimizer.cpp.o

src/core/Optimizer.i: src/core/Optimizer.cpp.i
.PHONY : src/core/Optimizer.i

# target to preprocess a source file
src/core/Optimizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/talawa-ai.dir/build.make CMakeFiles/talawa-ai.dir/src/core/Optimizer.cpp.i
.PHONY : src/core/Optimizer.cpp.i

src/core/Optimizer.s: src/core/Optimizer.cpp.s
.PHONY : src/core/Optimizer.s

# target to generate assembly for a file
src/core/Optimizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/talawa-ai.dir/build.make CMakeFiles/talawa-ai.dir/src/core/Optimizer.cpp.s
.PHONY : src/core/Optimizer.cpp.s

src/neuralnetwork/Conv2DLayer.o: src/neuralnetwork/Conv2DLayer.cpp.o
.PHONY : src/neuralnetwork/Conv2DLayer.o

# target to build an object file
src/neuralnetwork/Conv2DLayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/talawa-ai.dir/build.make CMakeFiles/talawa-ai.dir/src/neuralnetwork/Conv2DLayer.cpp.o
.PHONY : src/neuralnetwork/Conv2DLayer.cpp.o

src/neuralnetwork/Conv2DLayer.i: src/neuralnetwork/Conv2DLayer.cpp.i
.PHONY : src/neuralnetwork/Conv2DLayer.i

# target to preprocess a source file
src/neuralnetwork/Conv2DLayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/talawa-ai.dir/build.make CMakeFiles/talawa-ai.dir/src/neuralnetwork/Conv2DLayer.cpp.i
.PHONY : src/neuralnetwork/Conv2DLayer.cpp.i

src/neuralnetwork/Conv2DLayer.s: src/neuralnetwork/Conv2DLayer.cpp.s
.PHONY : src/neuralnetwork/Conv2DLayer.s

# target to generate assembly for a file
src/neuralnetwork/Conv2DLayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/talawa-ai.dir/build.make CMakeFiles/talawa-ai.dir/src/neuralnetwork/Conv2DLayer.cpp.s
.PHONY : src/neuralnetwork/Conv2DLayer.cpp.s

src/neuralnetwork/DenseLayer.o: src/neuralnetwork/DenseLayer.cpp.o
.PHONY : src/neuralnetwork/DenseLayer.o

# target to build an object file
src/neuralnetwork/DenseLayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/talawa-ai.dir/build.make CMakeFiles/talawa-ai.dir/src/neuralnetwork/DenseLayer.cpp.o
.PHONY : src/neuralnetwork/DenseLayer.cpp.o

src/neuralnetwork/DenseLayer.i: src/neuralnetwork/DenseLayer.cpp.i
.PHONY : src/neuralnetwork/DenseLayer.i

# target to preprocess a source file
src/neuralnetwork/DenseLayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/talawa-ai.dir/build.make CMakeFiles/talawa-ai.dir/src/neuralnetwork/DenseLayer.cpp.i
.PHONY : src/neuralnetwork/DenseLayer.cpp.i

src/neuralnetwork/DenseLayer.s: src/neuralnetwork/DenseLayer.cpp.s
.PHONY : src/neuralnetwork/DenseLayer.s

# target to generate assembly for a file
src/neuralnetwork/DenseLayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/talawa-ai.dir/build.make CMakeFiles/talawa-ai.dir/src/neuralnetwork/DenseLayer.cpp.s
.PHONY : src/neuralnetwork/DenseLayer.cpp.s

src/neuralnetwork/Loss.o: src/neuralnetwork/Loss.cpp.o
.PHONY : src/neuralnetwork/Loss.o

# target to build an object file
src/neuralnetwork/Loss.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/talawa-ai.dir/build.make CMakeFiles/talawa-ai.dir/src/neuralnetwork/Loss.cpp.o
.PHONY : src/neuralnetwork/Loss.cpp.o

src/neuralnetwork/Loss.i: src/neuralnetwork/Loss.cpp.i
.PHONY : src/neuralnetwork/Loss.i

# target to preprocess a source file
src/neuralnetwork/Loss.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/talawa-ai.dir/build.make CMakeFiles/talawa-ai.dir/src/neuralnetwork/Loss.cpp.i
.PHONY : src/neuralnetwork/Loss.cpp.i

src/neuralnetwork/Loss.s: src/neuralnetwork/Loss.cpp.s
.PHONY : src/neuralnetwork/Loss.s

# target to generate assembly for a file
src/neuralnetwork/Loss.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/talawa-ai.dir/build.make CMakeFiles/talawa-ai.dir/src/neuralnetwork/Loss.cpp.s
.PHONY : src/neuralnetwork/Loss.cpp.s

src/neuralnetwork/NeuralNetwork.o: src/neuralnetwork/NeuralNetwork.cpp.o
.PHONY : src/neuralnetwork/NeuralNetwork.o

# target to build an object file
src/neuralnetwork/NeuralNetwork.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/talawa-ai.dir/build.make CMakeFiles/talawa-ai.dir/src/neuralnetwork/NeuralNetwork.cpp.o
.PHONY : src/neuralnetwork/NeuralNetwork.cpp.o

src/neuralnetwork/NeuralNetwork.i: src/neuralnetwork/NeuralNetwork.cpp.i
.PHONY : src/neuralnetwork/NeuralNetwork.i

# target to preprocess a source file
src/neuralnetwork/NeuralNetwork.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/talawa-ai.dir/build.make CMakeFiles/talawa-ai.dir/src/neuralnetwork/NeuralNetwork.cpp.i
.PHONY : src/neuralnetwork/NeuralNetwork.cpp.i

src/neuralnetwork/NeuralNetwork.s: src/neuralnetwork/NeuralNetwork.cpp.s
.PHONY : src/neuralnetwork/NeuralNetwork.s

# target to generate assembly for a file
src/neuralnetwork/NeuralNetwork.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/talawa-ai.dir/build.make CMakeFiles/talawa-ai.dir/src/neuralnetwork/NeuralNetwork.cpp.s
.PHONY : src/neuralnetwork/NeuralNetwork.cpp.s

src/neuralnetwork/Pooling2DLayer.o: src/neuralnetwork/Pooling2DLayer.cpp.o
.PHONY : src/neuralnetwork/Pooling2DLayer.o

# target to build an object file
src/neuralnetwork/Pooling2DLayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/talawa-ai.dir/build.make CMakeFiles/talawa-ai.dir/src/neuralnetwork/Pooling2DLayer.cpp.o
.PHONY : src/neuralnetwork/Pooling2DLayer.cpp.o

src/neuralnetwork/Pooling2DLayer.i: src/neuralnetwork/Pooling2DLayer.cpp.i
.PHONY : src/neuralnetwork/Pooling2DLayer.i

# target to preprocess a source file
src/neuralnetwork/Pooling2DLayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/talawa-ai.dir/build.make CMakeFiles/talawa-ai.dir/src/neuralnetwork/Pooling2DLayer.cpp.i
.PHONY : src/neuralnetwork/Pooling2DLayer.cpp.i

src/neuralnetwork/Pooling2DLayer.s: src/neuralnetwork/Pooling2DLayer.cpp.s
.PHONY : src/neuralnetwork/Pooling2DLayer.s

# target to generate assembly for a file
src/neuralnetwork/Pooling2DLayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/talawa-ai.dir/build.make CMakeFiles/talawa-ai.dir/src/neuralnetwork/Pooling2DLayer.cpp.s
.PHONY : src/neuralnetwork/Pooling2DLayer.cpp.s

src/rl/QTable.o: src/rl/QTable.cpp.o
.PHONY : src/rl/QTable.o

# target to build an object file
src/rl/QTable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/talawa-ai.dir/build.make CMakeFiles/talawa-ai.dir/src/rl/QTable.cpp.o
.PHONY : src/rl/QTable.cpp.o

src/rl/QTable.i: src/rl/QTable.cpp.i
.PHONY : src/rl/QTable.i

# target to preprocess a source file
src/rl/QTable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/talawa-ai.dir/build.make CMakeFiles/talawa-ai.dir/src/rl/QTable.cpp.i
.PHONY : src/rl/QTable.cpp.i

src/rl/QTable.s: src/rl/QTable.cpp.s
.PHONY : src/rl/QTable.s

# target to generate assembly for a file
src/rl/QTable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/talawa-ai.dir/build.make CMakeFiles/talawa-ai.dir/src/rl/QTable.cpp.s
.PHONY : src/rl/QTable.cpp.s

src/utils/DataLoader.o: src/utils/DataLoader.cpp.o
.PHONY : src/utils/DataLoader.o

# target to build an object file
src/utils/DataLoader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/talawa-ai.dir/build.make CMakeFiles/talawa-ai.dir/src/utils/DataLoader.cpp.o
.PHONY : src/utils/DataLoader.cpp.o

src/utils/DataLoader.i: src/utils/DataLoader.cpp.i
.PHONY : src/utils/DataLoader.i

# target to preprocess a source file
src/utils/DataLoader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/talawa-ai.dir/build.make CMakeFiles/talawa-ai.dir/src/utils/DataLoader.cpp.i
.PHONY : src/utils/DataLoader.cpp.i

src/utils/DataLoader.s: src/utils/DataLoader.cpp.s
.PHONY : src/utils/DataLoader.s

# target to generate assembly for a file
src/utils/DataLoader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/talawa-ai.dir/build.make CMakeFiles/talawa-ai.dir/src/utils/DataLoader.cpp.s
.PHONY : src/utils/DataLoader.cpp.s

src/utils/Dataset.o: src/utils/Dataset.cpp.o
.PHONY : src/utils/Dataset.o

# target to build an object file
src/utils/Dataset.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/talawa-ai.dir/build.make CMakeFiles/talawa-ai.dir/src/utils/Dataset.cpp.o
.PHONY : src/utils/Dataset.cpp.o

src/utils/Dataset.i: src/utils/Dataset.cpp.i
.PHONY : src/utils/Dataset.i

# target to preprocess a source file
src/utils/Dataset.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/talawa-ai.dir/build.make CMakeFiles/talawa-ai.dir/src/utils/Dataset.cpp.i
.PHONY : src/utils/Dataset.cpp.i

src/utils/Dataset.s: src/utils/Dataset.cpp.s
.PHONY : src/utils/Dataset.s

# target to generate assembly for a file
src/utils/Dataset.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/talawa-ai.dir/build.make CMakeFiles/talawa-ai.dir/src/utils/Dataset.cpp.s
.PHONY : src/utils/Dataset.cpp.s

tests/cnn_mnist.test.o: tests/cnn_mnist.test.cpp.o
.PHONY : tests/cnn_mnist.test.o

# target to build an object file
tests/cnn_mnist.test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnn_mnist.test.dir/build.make CMakeFiles/cnn_mnist.test.dir/tests/cnn_mnist.test.cpp.o
.PHONY : tests/cnn_mnist.test.cpp.o

tests/cnn_mnist.test.i: tests/cnn_mnist.test.cpp.i
.PHONY : tests/cnn_mnist.test.i

# target to preprocess a source file
tests/cnn_mnist.test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnn_mnist.test.dir/build.make CMakeFiles/cnn_mnist.test.dir/tests/cnn_mnist.test.cpp.i
.PHONY : tests/cnn_mnist.test.cpp.i

tests/cnn_mnist.test.s: tests/cnn_mnist.test.cpp.s
.PHONY : tests/cnn_mnist.test.s

# target to generate assembly for a file
tests/cnn_mnist.test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnn_mnist.test.dir/build.make CMakeFiles/cnn_mnist.test.dir/tests/cnn_mnist.test.cpp.s
.PHONY : tests/cnn_mnist.test.cpp.s

tests/matrix.test.o: tests/matrix.test.cpp.o
.PHONY : tests/matrix.test.o

# target to build an object file
tests/matrix.test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix.test.dir/build.make CMakeFiles/matrix.test.dir/tests/matrix.test.cpp.o
.PHONY : tests/matrix.test.cpp.o

tests/matrix.test.i: tests/matrix.test.cpp.i
.PHONY : tests/matrix.test.i

# target to preprocess a source file
tests/matrix.test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix.test.dir/build.make CMakeFiles/matrix.test.dir/tests/matrix.test.cpp.i
.PHONY : tests/matrix.test.cpp.i

tests/matrix.test.s: tests/matrix.test.cpp.s
.PHONY : tests/matrix.test.s

# target to generate assembly for a file
tests/matrix.test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix.test.dir/build.make CMakeFiles/matrix.test.dir/tests/matrix.test.cpp.s
.PHONY : tests/matrix.test.cpp.s

tests/matrix_equality.test.o: tests/matrix_equality.test.cpp.o
.PHONY : tests/matrix_equality.test.o

# target to build an object file
tests/matrix_equality.test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix_equality.test.dir/build.make CMakeFiles/matrix_equality.test.dir/tests/matrix_equality.test.cpp.o
.PHONY : tests/matrix_equality.test.cpp.o

tests/matrix_equality.test.i: tests/matrix_equality.test.cpp.i
.PHONY : tests/matrix_equality.test.i

# target to preprocess a source file
tests/matrix_equality.test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix_equality.test.dir/build.make CMakeFiles/matrix_equality.test.dir/tests/matrix_equality.test.cpp.i
.PHONY : tests/matrix_equality.test.cpp.i

tests/matrix_equality.test.s: tests/matrix_equality.test.cpp.s
.PHONY : tests/matrix_equality.test.s

# target to generate assembly for a file
tests/matrix_equality.test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix_equality.test.dir/build.make CMakeFiles/matrix_equality.test.dir/tests/matrix_equality.test.cpp.s
.PHONY : tests/matrix_equality.test.cpp.s

tests/mnist.test.o: tests/mnist.test.cpp.o
.PHONY : tests/mnist.test.o

# target to build an object file
tests/mnist.test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mnist.test.dir/build.make CMakeFiles/mnist.test.dir/tests/mnist.test.cpp.o
.PHONY : tests/mnist.test.cpp.o

tests/mnist.test.i: tests/mnist.test.cpp.i
.PHONY : tests/mnist.test.i

# target to preprocess a source file
tests/mnist.test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mnist.test.dir/build.make CMakeFiles/mnist.test.dir/tests/mnist.test.cpp.i
.PHONY : tests/mnist.test.cpp.i

tests/mnist.test.s: tests/mnist.test.cpp.s
.PHONY : tests/mnist.test.s

# target to generate assembly for a file
tests/mnist.test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mnist.test.dir/build.make CMakeFiles/mnist.test.dir/tests/mnist.test.cpp.s
.PHONY : tests/mnist.test.cpp.s

tests/net.test.o: tests/net.test.cpp.o
.PHONY : tests/net.test.o

# target to build an object file
tests/net.test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net.test.dir/build.make CMakeFiles/net.test.dir/tests/net.test.cpp.o
.PHONY : tests/net.test.cpp.o

tests/net.test.i: tests/net.test.cpp.i
.PHONY : tests/net.test.i

# target to preprocess a source file
tests/net.test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net.test.dir/build.make CMakeFiles/net.test.dir/tests/net.test.cpp.i
.PHONY : tests/net.test.cpp.i

tests/net.test.s: tests/net.test.cpp.s
.PHONY : tests/net.test.s

# target to generate assembly for a file
tests/net.test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net.test.dir/build.make CMakeFiles/net.test.dir/tests/net.test.cpp.s
.PHONY : tests/net.test.cpp.s

tests/save_load.test.o: tests/save_load.test.cpp.o
.PHONY : tests/save_load.test.o

# target to build an object file
tests/save_load.test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/save_load.test.dir/build.make CMakeFiles/save_load.test.dir/tests/save_load.test.cpp.o
.PHONY : tests/save_load.test.cpp.o

tests/save_load.test.i: tests/save_load.test.cpp.i
.PHONY : tests/save_load.test.i

# target to preprocess a source file
tests/save_load.test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/save_load.test.dir/build.make CMakeFiles/save_load.test.dir/tests/save_load.test.cpp.i
.PHONY : tests/save_load.test.cpp.i

tests/save_load.test.s: tests/save_load.test.cpp.s
.PHONY : tests/save_load.test.s

# target to generate assembly for a file
tests/save_load.test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/save_load.test.dir/build.make CMakeFiles/save_load.test.dir/tests/save_load.test.cpp.s
.PHONY : tests/save_load.test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Matrix.benchmark"
	@echo "... cnn_mnist.test"
	@echo "... matrix.test"
	@echo "... matrix_equality.test"
	@echo "... mnist.test"
	@echo "... net.test"
	@echo "... save_load.test"
	@echo "... talawa-ai"
	@echo "... benchmarks/Matrix.benchmark.o"
	@echo "... benchmarks/Matrix.benchmark.i"
	@echo "... benchmarks/Matrix.benchmark.s"
	@echo "... src/core/Activation.o"
	@echo "... src/core/Activation.i"
	@echo "... src/core/Activation.s"
	@echo "... src/core/Initializer.o"
	@echo "... src/core/Initializer.i"
	@echo "... src/core/Initializer.s"
	@echo "... src/core/Matrix.o"
	@echo "... src/core/Matrix.i"
	@echo "... src/core/Matrix.s"
	@echo "... src/core/Optimizer.o"
	@echo "... src/core/Optimizer.i"
	@echo "... src/core/Optimizer.s"
	@echo "... src/neuralnetwork/Conv2DLayer.o"
	@echo "... src/neuralnetwork/Conv2DLayer.i"
	@echo "... src/neuralnetwork/Conv2DLayer.s"
	@echo "... src/neuralnetwork/DenseLayer.o"
	@echo "... src/neuralnetwork/DenseLayer.i"
	@echo "... src/neuralnetwork/DenseLayer.s"
	@echo "... src/neuralnetwork/Loss.o"
	@echo "... src/neuralnetwork/Loss.i"
	@echo "... src/neuralnetwork/Loss.s"
	@echo "... src/neuralnetwork/NeuralNetwork.o"
	@echo "... src/neuralnetwork/NeuralNetwork.i"
	@echo "... src/neuralnetwork/NeuralNetwork.s"
	@echo "... src/neuralnetwork/Pooling2DLayer.o"
	@echo "... src/neuralnetwork/Pooling2DLayer.i"
	@echo "... src/neuralnetwork/Pooling2DLayer.s"
	@echo "... src/rl/QTable.o"
	@echo "... src/rl/QTable.i"
	@echo "... src/rl/QTable.s"
	@echo "... src/utils/DataLoader.o"
	@echo "... src/utils/DataLoader.i"
	@echo "... src/utils/DataLoader.s"
	@echo "... src/utils/Dataset.o"
	@echo "... src/utils/Dataset.i"
	@echo "... src/utils/Dataset.s"
	@echo "... tests/cnn_mnist.test.o"
	@echo "... tests/cnn_mnist.test.i"
	@echo "... tests/cnn_mnist.test.s"
	@echo "... tests/matrix.test.o"
	@echo "... tests/matrix.test.i"
	@echo "... tests/matrix.test.s"
	@echo "... tests/matrix_equality.test.o"
	@echo "... tests/matrix_equality.test.i"
	@echo "... tests/matrix_equality.test.s"
	@echo "... tests/mnist.test.o"
	@echo "... tests/mnist.test.i"
	@echo "... tests/mnist.test.s"
	@echo "... tests/net.test.o"
	@echo "... tests/net.test.i"
	@echo "... tests/net.test.s"
	@echo "... tests/save_load.test.o"
	@echo "... tests/save_load.test.i"
	@echo "... tests/save_load.test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

